name: Network_Prod
run-name: ${{ github.actor }} is Validating Terraform project ðŸš€
on: 
  push:
    paths:
      - 'us-east-1/env/prod/network/**'
      - '.github/workflows/**'

jobs:
  network_prod:
    uses: ayrtonfidel9/aws-technical-test-tf/.github/workflows/terraform-workflow.yml@main
    with:
      component_path: 'us-east-1/env/prod/network'
